export const vehicleDefaults = {
  vehicleTypeId: "",
  seats: 0,
  titleName: "",
  photo: "",
  year: "",
  subType: "",
  currentLocation: "",
  color: "",
  vin: "",
  engineNumber: "",
  ifta: "",
  licenceNumber: "",
  registrationExpiry: "",
  cfn: "",
  titleUploadPic: "",
  character: "",
  fleetNumber: "",
  trim: "",
  make: "",
};

export const userDefaults = {
  name: "",
  email: "",
  role: 0,
  userName: "",
  emailVerified: "",
  image: "",
  profilePic: "",
  location: "",
};
